name: Android CI

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v3

      - name: Build & Static Checks
        run: |
          ./gradlew clean assembleDebug \
            detekt \
            ktlintCheck

      - name: Unit tests + Jacoco
        run: |
          ./gradlew testDebugUnitTest jacocoTestReport

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/tests/**/*
            **/build/reports/detekt/**/*
            **/build/reports/ktlint/**/*
            app/build/reports/jacoco/jacocoTestReport/**/*

      - name: Generate coverage badge (Jacoco)
        uses: cicirello/jacoco-badge-generator@v3
        with:
          jacoco-xml-file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          coverage-badge-filename: coverage.svg
          generate-branches-badge: false
          fail-if-coverage-less-than: 0

      - name: Commit badge
        if: github.event_name == 'push'
        run: |
          mkdir -p badges
          mv coverage.svg badges/coverage.svg
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/coverage.svg
          git commit -m "chore(ci): update coverage badge [skip ci]" || echo "No changes"
          git push

      - name: Job Summary
        if: always()
        run: |
          echo "### Cobertura (linhas)" >> $GITHUB_STEP_SUMMARY
          echo "![](badges/coverage.svg)" >> $GITHUB_STEP_SUMMARY
