name: Android CI

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3

      # --- Build & análises estáticas ---
      - name: Build & Static Checks
        run: |
          ./gradlew clean :app:assembleDebug \
            detekt \
            ktlintCheck \
            lint

      # --- Testes + cobertura (Kover) ---
      - name: Unit tests + Kover
        run: |
          ./gradlew :app:test :app:koverXmlReport :app:koverHtmlReport

      - name: Debug Kover outputs
        run: |
          find . -path "*/build/reports/kover/xml/report.xml" -print

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/build/reports/tests/**/*
            **/build/reports/detekt/**/*
            **/build/reports/ktlint/**/*
            **/build/reports/lint-results*.html
            **/build/reports/lint-results*.xml
            **/build/reports/kover/**/*

      - name: Generate coverage badge (Kover XML)
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-xml-file: '**/build/reports/kover/xml/report.xml'
          badges-directory: badges
          coverage-badge-filename: coverage.svg
          generate-branches-badge: false
          fail-if-coverage-less-than: 0

      - name: Commit badge
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add badges/coverage.svg
          git commit -m "chore(ci): update coverage badge [skip ci]" || echo "No changes"
          git push

      - name: Job Summary
        if: always()
        run: |
          echo "### Cobertura (linhas)" >> $GITHUB_STEP_SUMMARY
          echo "![](badges/coverage.svg)" >> $GITHUB_STEP_SUMMARY
